### ISSUE TITLE
2 issues, doesn't respect "size" in query, and added extra 'CRLF's in my CVS file 

### ISSUE THREAD

**Issue by teebu** [taraslayshchuk/es2csv#23]
Query had "size" param, this program ignored it. I had to use -m. 

When the CVS was generated, it has extra enters after each doc entry.

![image](https://cloud.githubusercontent.com/assets/5531844/23437155/eaaeb108-fdc1-11e6-8e69-abe3dbe654aa.png)

I should also include I am using this in Windows in Git Bash

**Comment by taraslayshchuk** [comment]
Hello

Looks like as Windows specific issue with end line symbol. As I don't have windows box I can not test it.
Could you please provide example query with "size"?

**Comment by teebu** [comment]
```
{
  "_source": { "include": ["@timestamp","agent","cs_uri_stem","uri_query","clientip"]},
  "size": 10,
  "query": {
    "bool": {
      "minimum_should_match": 1,
      "must": [],
      "must_not": [],
      "should": []
    }
  }  
}
```

**Comment by taraslayshchuk** [comment]
With [scroll api](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#search-request-scroll) the size parameter is used in another case:

> The size parameter allows you to configure the maximum number of hits to be returned with each batch of results. Each call to the scroll API returns the next batch of results until there are no more results left to return, i.e. the hits array is empty.

So you should use `--max 10` instead of size attribute.
By the way, 
`"_source": { "include": ["@timestamp","agent","cs_uri_stem","uri_query","clientip"]}`
can be replaces with `-f @timestamp agent cs_uri_stem uri_query clientip`

**Comment by teebu** [comment]
thanks
